"""Host network preparation for WireGuard's `host` variant (§6.1).

With `network_mode: host` on native Linux, the wg-easy container uses the
host's own network stack: packets arriving through the tunnel have to be
**forwarded** on to nginx and to the rest of the LAN. A kernel sysctl decides
that — `net.ipv4.ip_forward` — and on most distributions it ships off.

With forwarding off the failure is especially unpleasant to diagnose, because
nothing fails: the tunnel establishes, the WireGuard handshake succeeds, the
client shows as connected in the panel — and not one packet reaches its
destination. There is no error in any log, neither the container's nor the
host's.

`privileges.ELEVATION_REASONS` already advertised "apply the IP forwarding
`sysctl` for WireGuard (Linux)" and `docker-compose.yml.j2` itself points at
`/etc/sysctl.d/99-wireguard.conf`, but **nobody wrote it**: the wizard asked
for root privileges for work it then did not do. This module is that missing
part.

A file is written into `/etc/sysctl.d/` rather than just running `sysctl -w`
because `-w` does not survive a reboot and the stack does
(`restart: unless-stopped`): without the file, the VPN would stop routing at
the first reboot.
"""

from __future__ import annotations

import platform as _platform
from dataclasses import dataclass
from pathlib import Path

from axion_wizard.utils.shell import CommandNotFoundError, CommandTimeoutError, run

SYSCTL_CONF_PATH = Path("/etc/sysctl.d/99-wireguard.conf")

#: `net.ipv4.ip_forward` is the one that matters for the IPv4 tunnel, which
#: is what wg-easy sets up by default. The IPv6 one is included because a
#: client with IPv6 enabled will try to use it and, without forwarding, those
#: connections hang rather than falling back to IPv4.
SYSCTL_SETTINGS: dict[str, str] = {
    "net.ipv4.ip_forward": "1",
    "net.ipv6.conf.all.forwarding": "1",
}

SYSCTL_CONF_HEADER = (
    "# Generated by axion-wizard for WireGuard's `host` variant (§6.1).\n"
    "# Without IP forwarding the tunnel establishes and the handshake works,\n"
    "# but no packet reaches its destination — and no log shows an error.\n"
)


@dataclass
class ForwardingResult:
    """What could be done about IP forwarding, for the caller to decide on.

    No exception is ever raised from here: broken forwarding leaves the VPN
    unable to route, but the rest of the stack (Mattermost, the AI, LAN
    access) works perfectly. Aborting the whole install over this would be
    worse than finishing it with a warning.
    """

    applied: bool
    active: bool
    conf_written: bool
    detail: str

    @property
    def needs_attention(self) -> bool:
        return not self.active


def is_applicable(os_name: str, wireguard_variant: str) -> bool:
    """IP forwarding is only needed on Linux with `network_mode: host`.

    In the `ports` variant Docker routes the packets through its own NAT, and
    on Windows/macOS the kernel that matters is the Docker Desktop VM's, not
    the host's — touching sysctls there would have no effect at all.
    """
    from axion_wizard.domain.config import WireguardVariant

    return os_name == "Linux" and wireguard_variant == WireguardVariant.HOST.value


def read_runtime_value(key: str, proc_root: Path = Path("/proc/sys")) -> str | None:
    """A sysctl's effective value, read from `/proc/sys`, or `None`.

    Read from the kernel rather than from the files in `/etc/sysctl.d/`: what
    matters is what is active *now*, not what somebody left written down.
    """
    path = proc_root / Path(key.replace(".", "/"))
    try:
        return path.read_text().strip()
    except OSError:
        return None


def forwarding_is_active(proc_root: Path = Path("/proc/sys")) -> bool:
    """`True` if every sysctl in `SYSCTL_SETTINGS` is already applied.

    A sysctl that cannot be read does not count as active: on a kernel built
    without IPv6, `net.ipv6.conf.all.forwarding` does not exist.
    """
    for key, expected in SYSCTL_SETTINGS.items():
        current = read_runtime_value(key, proc_root=proc_root)
        if current is None:
            # The IPv4 one always exists; the IPv6 one may not. Only the one
            # that genuinely breaks the tunnel is required.
            if key.startswith("net.ipv4."):
                return False
            continue
        if current != expected:
            return False
    return True


def render_sysctl_conf() -> str:
    lines = [SYSCTL_CONF_HEADER]
    lines += [f"{key} = {value}\n" for key, value in SYSCTL_SETTINGS.items()]
    return "".join(lines)


def _apply_with_sysctl(conf_path: Path, timeout: float = 15.0) -> tuple[bool, str]:
    """Apply the freshly written file without waiting for a reboot.

    `sysctl -p <file>` is tried first because it is narrow and does not
    revalidate all of `/etc/sysctl.d`, where somebody else's malformed file
    would fail the whole operation over something that is not ours.
    """
    for args in (["sysctl", "-p", str(conf_path)], ["sysctl", "--system"]):
        try:
            result = run(args, timeout=timeout)
        except (CommandNotFoundError, CommandTimeoutError) as exc:
            return False, str(exc)
        if result.ok:
            return True, " ".join(args)
    return False, f"`{' '.join(args)}` exited with an error"


def ensure_ip_forwarding(
    conf_path: Path = SYSCTL_CONF_PATH,
    proc_root: Path = Path("/proc/sys"),
    dry_run: bool = False,
) -> ForwardingResult:
    """Leave IP forwarding active and persistent. Never raises.

    Idempotent: if it is already active and the file has the right contents,
    nothing is touched. If there are no permissions — `--no-elevate`, or a
    declined `sudo` — the reason is returned so the step can show it as a
    warning.
    """
    already_active = forwarding_is_active(proc_root=proc_root)
    desired = render_sysctl_conf()

    if dry_run:
        return ForwardingResult(
            applied=False,
            active=already_active,
            conf_written=False,
            detail=f"would write {conf_path} and apply {', '.join(SYSCTL_SETTINGS)}",
        )

    conf_written = False
    try:
        if not conf_path.exists() or conf_path.read_text(encoding="utf-8") != desired:
            conf_path.parent.mkdir(parents=True, exist_ok=True)
            conf_path.write_text(desired, encoding="utf-8")
            conf_written = True
    except OSError as exc:
        # Without the file we lose persistence at worst; forwarding may
        # already be active by another route, so this is not given up on.
        return ForwardingResult(
            applied=False,
            active=already_active,
            conf_written=False,
            detail=f"could not write {conf_path} ({exc}); root is required",
        )

    if already_active and not conf_written:
        return ForwardingResult(
            applied=True, active=True, conf_written=False, detail="was already active"
        )

    applied, how = _apply_with_sysctl(conf_path)
    active = forwarding_is_active(proc_root=proc_root)
    if applied and active:
        return ForwardingResult(
            applied=True, active=True, conf_written=conf_written, detail=f"applied with {how}"
        )
    if active:
        # `sysctl` failed but the value is right: how it got there is moot.
        return ForwardingResult(
            applied=True, active=True, conf_written=conf_written, detail="active in the kernel"
        )
    return ForwardingResult(
        applied=False,
        active=False,
        conf_written=conf_written,
        detail=f"{conf_path} written, but the sysctl never took effect ({how})",
    )


def describe_manual_fix(conf_path: Path = SYSCTL_CONF_PATH) -> list[str]:
    """The same steps, by hand, for when the wizard has no privileges."""
    settings = " ".join(f"{key}={value}" for key, value in SYSCTL_SETTINGS.items())
    return [
        f"Write {conf_path} with: {', '.join(f'{k} = {v}' for k, v in SYSCTL_SETTINGS.items())}",
        f"Apply it without rebooting: sudo sysctl -w {settings}",
        "Or rerun the wizard with privileges: sudo axion-wizard install",
    ]


def current_os_name() -> str:
    return _platform.system()
