"""Helpers shared by more than one command module."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from axion_wizard.errors import ConfigError
from axion_wizard.render.console import console

if TYPE_CHECKING:
    from axion_wizard.cli import GlobalState

CERT_RELATIVE_DIR = Path("nginx") / "certs"
COMPOSE_FILENAME = "docker-compose.yml"


def compose_path_of(state: GlobalState) -> Path:
    """The project's compose path, checked for existence before Docker fails
    with a far less clear message."""
    path = state.project_dir / COMPOSE_FILENAME
    if not path.exists():
        raise ConfigError(
            what=f"Could not find {path}",
            why="This subcommand operates on a stack already generated by `axion-wizard install`.",
            steps=[
                "Run `axion-wizard install` first.",
                "Or point at the right directory with --project-dir.",
            ],
        )
    return path


def announce_dry_run(action: str) -> None:
    console.print(f"[axion.info][dry-run][/] {action}")
